#!/bin/sh
#lp install 
#written by xiewei 2004 
#modified by lty 2018

lp_dir=~/.lp
bin_dir=/usr/local/sbin
prof_dir=/etc/profile.d

setup()
{
    if [ -e $history_dir ]
    then	
 	echo -n "You have installed lp , overwrite it(y\Y or n\N)? "
 	read choice
        if [ $choice = "n" -o $choice = "N" ]
        then
	    cp -f ./lp $bin_dir/
	    cp -f ./lp.sh $prof_dir/
	    echo "install lp OK, but do not overwrite it!"
	    echo "version is 1.00"
	    exit 0
        fi
    fi

    if [ ! -e $lp_dir ]
	mkdir $lp_dir
    fi
    
    cp -f ./lp $bin_dir/
    cp -f ./lp.sh $prof_dir/
    cp -f ./history_dir $lp_dir/
}

delete()
{
    echo -n "Are you sure to delete lp(y\Y or n\N)? "
    read choice
    if [ "$choice" = "N" -o "$choice" = "n" ]
    then
	echo "Nothing to do!"
	exit 0
    fi

    rm -rf $lp_dir
    rm -f  $bin_dir/lp
    rm -f  $prof_dir/lp.sh
}

usage()
{
    echo "<install> install lp on your computer."
    echo "<install del> delete lp from your computer."
    exit 1
}

echo "Installing Software lp"
echo "Written By XieWei 2004" 
echo "Re-implemented By lty at Dec31th, 2018" 

if [ $# -eq 0 ]
then
    setup
    echo "lp is installed successfully!"
    echo "version is 1.00"
    exit 0
else if [ $# -gt 1 ]
then
    usage
else
    case $1 in
    del)
        delete
        echo "have delete lp OK!"
        ;;
    *)
        usage
        ;;
    esac
fi 



